#!/usr/bin/env python3
"""Generate the site from the archived CrazyGames 2026 shell.

Rather than approximating the 2026 look, the pages here reuse the archived
markup and the archived stylesheet (assets/cg2026/theme.css, fetched by
tools/fetch-2026.py). Only two things differ from the archive:

  * branding  - our logo, our name, our favicon (no CrazyGames marks)
  * content   - our catalogue from data/games.json, and our own player

Everything else (header height, rail width, card geometry, the game page's
main+sidebar split, type scale) is the archive's own CSS doing the work, so it
matches 1:1 instead of being eyeballed.

    python3 tools/fetch-2026.py        # once: pull css/fonts/icons
    python3 tools/build-archive.py     # then: emit the pages
"""
import datetime
import hashlib
import html
import json
import os
import collections

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA_FILE = os.path.join(ROOT, "data", "games.json")
CG26 = "assets/cg2026"

# Filled-heart path used by the card favourite overlay. The same shape is
# inlined in cg-site.js for the client-rendered cards.
HEART_PATH = ("M12 21C11.11 21 10.11 20.5 9.21 19.9C8.27 19.26 7.25 18.38 6.30 "
              "17.36C4.41 15.35 2.61 12.66 2.11 10.09C1.92 9.10 1.91 7.38 2.70 "
              "5.86C3.11 5.08 3.72 4.35 4.63 3.82C5.53 3.30 6.66 3 8.04 3C9.62 3 "
              "11.05 3.62 12 4.64C12.95 3.62 14.38 3 15.96 3C17.34 3 18.47 3.30 "
              "19.37 3.82C20.28 4.35 20.89 5.08 21.30 5.86C22.09 7.38 22.08 9.10 "
              "21.89 10.09C21.39 12.66 19.59 15.35 17.70 17.36C16.75 18.38 15.73 "
              "19.26 14.79 19.90C13.89 20.50 12.89 21 12 21Z")

# Cache-busting token for the local stylesheet/scripts. It is derived from the
# asset contents in main(), not hand-maintained: the old fixed "v=28" let a
# rebuilt cg.css sit behind a 4h max-age while the HTML (10min) updated, so
# returning visitors rendered the new markup with stale styles.
VERSION = "0"
BUILD_STAMP = datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%d %H:%M:%SZ")
MARKER = ("<!-- Generated by tools/build-archive.py - edit that script, not this file. -->\n"
          f"<!-- build {BUILD_STAMP} -->")


def asset_version(games_js):
    """sha1 of everything the pages link, so any change busts the cache."""
    h = hashlib.sha1()
    h.update(games_js.encode("utf-8"))
    for rel in ("assets/css/cg.css", "assets/css/cg-play.css", "assets/css/sga-play.css", "assets/js/cg-site.js", "assets/cg2026/theme.css"):
        try:
            with open(os.path.join(ROOT, rel), "rb") as fh:
                h.update(fh.read())
        except OSError:
            pass
    return h.hexdigest()[:10]

# --- rail (2026 sidebar entries; category hrefs map to our catalogue) ---------
RAIL = [
    ("Home", "./", "Home", True),
    ("Recently Played", "./?recent=1", "Recent", True),
    ("New", "./?sort=newest", "New", False),
    ("Hot Games", "./?sort=rating", "Trending", False),
    ("__hr__",),
    ("Action", "./?category=Action", "Action", False),
    ("Adventure", "./?category=Adventure", "Adventure", False),
    ("2 Player", "./?category=Team", "Multiplayer", False),
    ("Arcade", "./?category=Casual", "Casual", False),
    ("Board", "./?category=Board", "Board", False),
    ("Card", "./?category=Card", "Card", False),
    ("Puzzle", "./?category=Puzzle", "Puzzle", False),
    ("Shooting", "./?category=Shooter", "Shooting", False),
    ("Sports", "./?category=Sports", "Sports", False),
    ("Racing", "./?category=Racing", "Driving", False),
    ("Strategy", "./?category=Strategy", "Strategy", False),
    (".io", "./?category=Agario%20Style", "io", False),
]

def esc(s):
    return html.escape(str(s), quote=True)


def load_games():
    with open(DATA_FILE, encoding="utf-8") as f:
        games = json.load(f)
    for i, g in enumerate(games):
        g["_i"] = i
        g.setdefault("categories", [])
        g.setdefault("rating", None)
    return games


def play_url(g):
    return "./" + g["slug"]


# ---------------------------------------------------------------- page pieces --

def head(title, description, extra_css=""):
    return f"""  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{esc(title)}</title>
  <meta name="description" content="{esc(description)}">
  <meta name="theme-color" content="#0c0d14">
  <link rel="icon" href="assets/img/favicon.png" type="image/png">
  <link href="{CG26}/theme.css?v={VERSION}" rel="stylesheet">
  <link href="assets/css/cg.css?v={VERSION}" rel="stylesheet">{extra_css}"""


def header():
    """2026 shell header (Header_root): 60px, logo left, centred search,
    icon buttons right. Class names come from the archived 2026 portal so the
    archived stylesheet drives the look; branding and actions are ours."""
    return f"""  <header id="czyHeader" class="Header_root__uPVep cg-header">
    <div class="Header_leftSection__iw1d6">
      <a href="./" aria-label="Games home">
        <img class="LogoImage_logoImage__QD3zH" src="assets/img/logo.png"
             width="58" height="28" alt="Games" id="logo">
      </a>
    </div>
    <form class="TopSearch_topSearchForm__b9Z8c TopSearch_isDesktop__2eSKm cg-search"
          role="search" autocomplete="off" onsubmit="return false;">
      <div class="TopSearch_inputWrapper__QI6kt">
        <input class="TopSearch_searchInput__Nbapa TopSearch_topSearchInput__mCCPQ
               TopSearch_isDesktop__2eSKm" id="search-input" type="text"
               placeholder="Search games and categories" aria-label="Search games"
               autocomplete="off" spellcheck="false" aria-autocomplete="none"
               aria-controls="cgSearchResults">
        <div class="QuickSearchIcon_iconButton__t8cVX TopSearch_quickSearchIconDesktop__hbiT5">
          <span role="img" aria-hidden="true"
                class="Icon_icon__OracF Icon_icon-search___meL2 Icon_size20__yF8AY"></span>
        </div>
        <div class="cg-search-results" id="cgSearchResults" role="listbox" hidden></div>
      </div>
    </form>
    <div class="Header_rightSection__fcQ4k">
      <button class="Button_czyButton__y8IRs Button_czyButton--contained--grey__sz05o Button_czyButton--headerIcon__aK8wL Button_czyButton--headerIcon--desktop___7kXV cg-admin-link"
              type="button" aria-label="Admin panel" title="Admin panel">
        <span role="img" aria-hidden="true"
              class="Icon_icon__OracF Icon_icon-settings__4qq6P Icon_size20__yF8AY"></span>
      </button>
      <button class="Button_czyButton__y8IRs Button_czyButton--contained--grey__sz05o Button_czyButton--headerIcon__aK8wL Button_czyButton--headerIcon--desktop___7kXV cg-fav-btn"
              type="button" aria-label="Favorites" title="Favorites"
              aria-haspopup="dialog" aria-controls="cgFavPanel">
        <span role="img" aria-hidden="true"
              class="Icon_icon__OracF Icon_icon-heart__qO3Kr Icon_size20__yF8AY"></span>
      </button>
      <a class="Button_czyButton__y8IRs Button_czyButton--contained--grey__sz05o Button_czyButton--headerIcon__aK8wL Button_czyButton--headerIcon--desktop___7kXV"
         href="./?random=1" aria-label="Random game" title="Random game">
        <span role="img" aria-hidden="true"
              class="Icon_icon__OracF Icon_icon-surprise-random__QyKgX Icon_size20__yF8AY"></span>
      </a>
      <a class="Button_czyButton__y8IRs Button_czyButton--contained--grey__sz05o Button_czyButton--headerIcon__aK8wL Button_czyButton--headerIcon--desktop___7kXV"
         href="./about" aria-label="About" title="About">
        <span role="img" aria-hidden="true"
              class="Icon_icon__OracF Icon_icon-question-circle__4qTFO Icon_size20__yF8AY"></span>
      </a>
    </div>
  </header>"""


def rail(active=""):
    rows = []
    for item in RAIL:
        if item[0] == "__hr__":
            rows.append('      <div class="Sidebar_divider__imtDG" role="separator"></div>')
            continue
        label, href, icon_name, _ = item
        on = " Sidebar_active__bltDp cg-active" if label.lower() == active.lower() else ""
        rows.append(
            f'      <a class="Sidebar_link__Tbdup cg-rail-item{on}" href="{href}"'
            f' aria-label="{esc(label)}">'
            f'<img src="{CG26}/icons/{icon_name}.svg" loading="lazy" alt="{esc(label)} icon">'
            f'<div class="Sidebar_labelContainer__qHPDa">{esc(label)}</div></a>')
    return f"""  <nav id="mainNav" class="Sidebar_main___ex0V Sidebar_isDesktop__aieVO cg-rail" aria-label="Main">
    <div class="Sidebar_container__CqXNx" id="sidebarContainer">
{chr(10).join(rows)}
    </div>
  </nav>"""


def fav_btn(g):
    """The heart overlay on a card. cg-site.js wires the click (it must not open
    the game) and reflects the saved state."""
    return (
        f'<button class="cg-fav" type="button" data-fav="{esc(g["slug"])}" '
        f'aria-label="Add to favourites" aria-pressed="false" '
        f'title="Add to favourites"><svg viewBox="0 0 24 24" aria-hidden="true">'
        f'<path fill-rule="evenodd" d="{HEART_PATH}"></path></svg></button>')


def card(g):
    """A CrazyGames-2026 game thumb: an image-only link with the title in the
    aria-label, an optional new/hot badge and a hover-zoom overlay."""
    title = esc(g["title"])
    href = play_url(g)
    idx = g.get("_i", 0)
    label = ""
    if idx % 5 == 1:
        label = ('<div aria-label="New" class="GameThumbLabel_label__dz3yR '
                 'GameThumbLabel_new__8GnG6"><span role="img" aria-hidden="true" '
                 'class="Icon_icon__OracF Icon_icon-new__vmtCf Icon_size20__yF8AY">'
                 '</span></div>')
    elif idx % 5 == 3:
        label = ('<div aria-label="Hot" class="GameThumbLabel_label__dz3yR '
                 'GameThumbLabel_hot__CWhxn"><span role="img" aria-hidden="true" '
                 'class="Icon_icon__OracF Icon_icon-hot__Tir31 Icon_size20__yF8AY">'
                 '</span></div>')
    return (
        f'<a class="GameThumbDesktop_gameThumbLinkDesktop__LS_Bs '
        f'GameThumbDesktop_hasHoverOverlay__qNdmo game-thumb-test-class" '
        f'aria-label="{title}" href="{href}">{label}{fav_btn(g)}'
        f'<div class="GameThumbDesktop_gameThumbMedia__L7si1">'
        f'<img class="GameThumbShared_gameThumbImage__7EHHi '
        f'GameThumbShared_gameThumbImagePositioned__LJJut" loading="lazy" '
        f'alt="{title}" width="273" src="{esc(g["thumb"])}"></div></a>')


def carousel(title, games, more_href="", highlighted=False, row="", track_id="",
             title_html="", data_cat="", testid="", hidden=False, title_cls=""):
    """A 2026 carousel section. `title_html` overrides the plain title when the
    heading carries markup (e.g. a link or the country flag)."""
    cls = "CrazyCarousel_gamesCarouselSection__cDN02"
    if highlighted:
        cls += " CrazyCarousel_isHighlightedMode__R_Xpi"
    attrs = f' data-row="{row}"' if row else ""
    if testid:
        attrs += f' data-testid="{testid}"'
    if hidden:
        attrs += " hidden"
    tid = f' id="{track_id}"' if track_id else ""
    cat = f' data-cat="{esc(data_cat)}"' if data_cat else ""
    head = title_html or esc(title)
    tcls = "CarouselSectionTitle_carouselTitle__tDEqL"
    if title_cls:
        tcls += " " + title_cls
    more = (f'<a class="cg-more" href="{more_href}">View more</a>'
            if more_href else "")
    items = "\n".join(f"          <li>{card(g)}</li>" for g in games)
    return f"""      <section class="{cls}"{attrs}>
        <div class="cg-title-row">
          <div class="{tcls}">{head}</div>{more}
        </div>
        <div class="CrazyCarousel_crazyCarouselRoot__l3JCg">
          <ul class="CrazyCarousel_crazyCarouselContainer__63ph_ crazy-carousel"{tid}{cat}>
{items}
          </ul>
        </div>
      </section>"""


def two_row_carousel(title, row, track_id, more_href="", testid=""):
    """Two stacked scrollers under one title, each a standard 2026 carousel so
    the card size is unchanged. The client splits the games across the tracks."""
    attrs = f' data-row="{row}"' if row else ""
    if testid:
        attrs += f' data-testid="{testid}"'
    more = (f'<a class="cg-more" href="{more_href}">View more</a>'
            if more_href else "")
    return f"""      <section class="CrazyCarousel_gamesCarouselSection__cDN02 cg-two-row"{attrs}>
        <div class="cg-title-row">
          <div class="CarouselSectionTitle_carouselTitle__tDEqL">{esc(title)}</div>{more}
        </div>
        <div class="CrazyCarousel_crazyCarouselRoot__l3JCg">
          <ul class="CrazyCarousel_crazyCarouselContainer__63ph_ crazy-carousel" id="{track_id}"></ul>
        </div>
        <div class="CrazyCarousel_crazyCarouselRoot__l3JCg">
          <ul class="CrazyCarousel_crazyCarouselContainer__63ph_ crazy-carousel" id="{track_id}-2"></ul>
        </div>
      </section>"""


def hero_carousel(title, row, track_id, testid=""):
    """The highlighted "Top games today" strip: one big card then a column of
    two small cards, repeating. The client fills the track with a grid."""
    attrs = f' data-row="{row}"' if row else ""
    if testid:
        attrs += f' data-testid="{testid}"'
    return f"""      <section class="CrazyCarousel_gamesCarouselSection__cDN02 CrazyCarousel_isHighlightedMode__R_Xpi"{attrs}>
        <div class="cg-title-row">
          <div class="CarouselSectionTitle_carouselTitle__tDEqL RecommendedCarouselTitle_recommendedTitle__M_lew"><span>{esc(title)}</span></div>
        </div>
        <div class="CrazyCarousel_crazyCarouselRoot__l3JCg">
          <ul class="CrazyCarousel_crazyCarouselContainer__63ph_ crazy-carousel cg-hero-track" id="{track_id}"></ul>
        </div>
      </section>"""


def grid_section(title, games, more_href=""):
    more = (f'<a class="cg-more" href="{more_href}">View more</a>'
            if more_href else "")
    items = "\n".join(f"          <li>{card(g)}</li>" for g in games)
    return f"""      <section class="cg-section">
        <div class="cg-section-head">
          <h2 class="cg-section-title">{esc(title)}</h2>{more}
        </div>
        <ul class="cg-grid">
{items}
        </ul>
      </section>"""


def footer():
    return """  <footer class="cg-footer">
    <div class="cg-footer-inner">
      <p class="cg-footer-name">Games</p>
      <p class="cg-footer-note">A free browser games portal.</p>
    </div>
  </footer>"""


def admin_dialog(with_close=True):
    """Admin search/rate dialog, shared by the modal and the standalone page."""
    close = """        <button class="cg-admin-close" type="button" aria-label="Close admin panel">
          <svg viewBox="0 0 24 24" width="20" height="20" fill="currentColor" aria-hidden="true"><path d="M19 6.41 17.59 5 12 10.59 6.41 5 5 6.41 10.59 12 5 17.59 6.41 19 12 13.41 17.59 19 19 17.59 13.41 12z"/></svg>
        </button>""" if with_close else ""
    return f"""      <div class="cg-admin-head">
        <h2 class="cg-admin-title">Admin panel</h2>
{close}
      </div>
      <p class="cg-admin-note">Search the catalogue and click a star to set a game's
        rating. Ratings are saved in this browser and shown on the play page.</p>
      <input class="cg-admin-search" type="search" placeholder="Search games to rate"
             aria-label="Search games to rate" autocomplete="off">
      <ul class="cg-admin-results"></ul>"""


def admin_modal():
    """Overlay version, present on every page and opened with Ctrl+Alt+A."""
    return f"""  <div class="cg-admin" id="cgAdmin" role="dialog" aria-modal="true"
       aria-label="Admin panel" hidden>
    <div class="cg-admin-dialog">
{admin_dialog()}
    </div>
  </div>"""


def favorites_modal():
    """Header-popup version of the favourites list, present on every page."""
    return """  <div class="cg-fav-modal" id="cgFavPanel" role="dialog" aria-modal="true"
       aria-label="Favorites" hidden>
    <div class="cg-fav-dialog">
      <div class="cg-admin-head">
        <h2 class="cg-admin-title">Favorites</h2>
        <button class="cg-admin-close" type="button" aria-label="Close favorites">
          <svg viewBox="0 0 24 24" width="20" height="20" fill="currentColor" aria-hidden="true"><path d="M19 6.41 17.59 5 12 10.59 6.41 5 5 6.41 10.59 12 5 17.59 6.41 19 12 13.41 17.59 19 19 17.59 13.41 12z"/></svg>
        </button>
      </div>
      <p class="cg-fav-count" id="cgFavCount"></p>
      <p class="cg-fav-empty" id="cgFavEmpty" hidden>
        You haven't saved any games yet. Tap the heart on a game card to keep it
        here.
      </p>
      <ul class="cg-fav-grid" id="cgFavGrid"></ul>
      <p class="cg-fav-clear-wrap">
        <button class="cg-btn" type="button" id="cgFavClear" hidden>Clear all</button>
      </p>
    </div>
  </div>"""


def page(title, description, main, scripts, rail_active="Home", main_class="",
         admin_overlay=True, head_extra="", body_class="", body_attr=""):
    cls = ("cg-main " + main_class).strip()
    modal = admin_modal() if admin_overlay else ""
    body_attrs = (' class="' + body_class + '"' if body_class else "") + body_attr
    return f"""<!doctype html>
<html lang="en">
<head>
{MARKER}
{head(title, description)}
{head_extra}</head>
<body{body_attrs}>
  <div class="Layout_root__ggW6Q cg-shell">
{header()}

{rail(rail_active)}

    <main class="Layout_styledMain__YQszE Layout_isDesktop__1G5Sd Layout_hasCollapsedSidebar__AK3eb {cls}">
{main}
    </main>
  </div>

{footer()}
{modal}
{favorites_modal()}

  <script defer src="assets/js/cg-games.js?v={VERSION}"></script>
  <script defer src="assets/js/cg-site.js?v={VERSION}"></script>
  <script defer src="assets/js/cg-admin.js?v={VERSION}"></script>{scripts}
</body>
</html>
"""


# ------------------------------------------------------------------- builders --

def build_home(games):
    # The catalogue is ~84k games, so the page ships the data (cg-games.js) and
    # lets cg-site.js render the cards into the exact CrazyGames-2026 home
    # skeleton: a stack of carousels whose markup/classes come from the archived
    # 2026 portal (see tools/fetch-2026.py). Server-rendering every card would
    # make index.html megabytes of markup for a grid the client filters anyway.
    parts = []

    # "Continue playing" — filled from localStorage, hidden until it has history.
    parts.append("""      <section class="CrazyCarousel_gamesCarouselSection__cDN02"
        data-row="recent" id="cgRecentSection" data-testid="carousel-recent" hidden>
        <div class="CarouselSectionTitle_carouselTitle__tDEqL">Continue playing</div>
        <div class="CrazyCarousel_crazyCarouselRoot__l3JCg">
          <ul class="CrazyCarousel_crazyCarouselContainer__63ph_ crazy-carousel"
            id="cgRecentTrack"></ul>
        </div>
      </section>""")

    # Spotlight — one big card then a column of two small cards, repeating.
    parts.append(hero_carousel("Top games today", row="hero",
                               track_id="cgHeroCards",
                               testid="carousel-recommended"))

    parts.append(two_row_carousel("New games", row="new", track_id="cgNewTrack",
                                  testid="carousel-new-games",
                                  more_href="./?sort=newest"))
    parts.append(two_row_carousel("Trending now", row="trending",
                                  track_id="cgTrendTrack",
                                  testid="carousel-trending",
                                  more_href="./?sort=rating"))
    parts.append(carousel("Top games", [], row="top", track_id="cgTopTrack",
                          testid="carousel-top", more_href="./?sort=rating"))

    rows = [
        (".io Games", "Agario Style"),
        ("Action Games", "Action"),
        ("Puzzle Games", "Puzzle"),
        ("Shooting Games", "Shooter"),
        ("Sports Games", "Sports"),
        ("Racing Games", "Racing"),
        ("Casual Games", "Casual"),
    ]
    for label, cat in rows:
        parts.append(carousel(
            label, [], row="cat", data_cat=cat, testid="carousel-lazy-category",
            more_href="./?category=" + cat.replace(" ", "%20")))

    parts.append("""      <section class="cg-section" data-row="best">
        <div class="cg-section-head">
          <h2 class="cg-section-title">Play our best games</h2>
        </div>
        <ul class="cg-grid" id="cgBestGrid"></ul>
      </section>""")

    # Every game, rendered in pages by the client so the DOM stays small. A big
    # category (Casual ~25k) would otherwise build every card and image at once.
    parts.append("""      <section class="cg-section" id="cgAllGames" hidden>
        <div class="cg-section-head">
          <h2 class="cg-section-title" id="cgAllTitle">All games</h2>
          <span class="cg-more" id="cgAllCount"></span>
        </div>
        <ul class="cg-grid" id="cgAllGrid"></ul>
        <p class="cg-loadmore-wrap">
          <button class="cg-btn" type="button" id="cgAllMore" hidden>Load more</button>
        </p>
      </section>""")

    parts.append("""      <section class="cg-seo" id="cgSeo">
        <h1>Free Online Games</h1>
        <p>Games features thousands of free online games you can play instantly in
          your browser. No downloads, no installs, no pop-ups.</p>
        <p>Play action, puzzle, shooting, sports, racing and casual games on desktop
          and mobile, with new titles added all the time.</p>
        <button class="cg-seo-toggle" type="button" aria-expanded="false"
          aria-controls="cgSeo">Show more</button>
      </section>""")

    body = "      <div class=\"HomePage_root__6VHY8 HomePage_desktop__CDZV_\">\n" \
           + "\n".join(parts) + "\n      </div>"
    return page("Games - Free Online Games",
                "Play free browser games: action, puzzle, shooting, sports and more.",
                body, "", "Home", "cg-main-home",
                body_class="cg-2026")


def build_play(games):
    # 1:1 with sportsgamesaz.io/2v2io: the page body is the archived reference
    # DOM (tools/play_body.py) with the game-specific slots tokenised. Our
    # catalogue fills the sidebar; the player iframe and the footer action bar
    # are the reference's own markup and the reference stylesheet drives them.
    from play_body import PLAY_BODY

    head_extra = (f'  <link href="assets/css/sga-play.css?v={VERSION}" rel="stylesheet">\n')
    scripts = f'\n  <script defer src="assets/js/cg-detail.js?v={VERSION}"></script>'
    return page("Play - Games", "Play a free browser game.",
                "      " + PLAY_BODY.strip(), scripts, "Home", "cg-main-play",
                head_extra=head_extra)
def build_about(games):
    total = len(games)
    cats = collections.Counter(c for g in games for c in g.get("categories", []))
    top_cats = [c for c, _ in cats.most_common(14)]
    sources = len({g.get("source") for g in games if g.get("source")})

    cat_chips = "\n".join(
        f'          <a class="cg-chip" href="./?category={esc(c).replace(" ", "%20")}">{esc(c)}</a>'
        for c in top_cats)

    faqs = [
        ("Is it really free to play?",
         "Yes. Every game on Games runs in your browser at no cost, with no "
         "account and no download. The catalogue is funded by the game "
         "providers themselves, so nothing is hidden behind a paywall."),
        ("Do I need to install anything?",
         "No installs, no plugins, no launchers. Games are built with HTML5 and "
         "WebGL, so if your browser is up to date you can start playing in one "
         "click."),
        ("Can I play on my phone or tablet?",
         "Most titles are touch-friendly and scale to any screen. A few are "
         "designed for keyboard and mouse, so for those a desktop is the best "
         "experience."),
        ("How do I save a game for later?",
         "Tap the heart on any game card. Your picks are stored in this browser "
         "and appear under Favorites in the header, and the games you play most "
         "recently show up in Continue playing on the home page."),
        ("Are new games added?",
         "Constantly. New and updated titles flow in from the providers we "
         "partner with, and the New and Trending rows on the home page surface "
         "the freshest additions first."),
        ("Who makes the games?",
         "The games are created by independent studios and publishers around the "
         "world. Games brings them together in one fast, clean place to play. "
         "The Source line on each game page credits where it came from."),
    ]
    faq_html = "\n".join(
        f"""          <details>
            <summary>{esc(q)}</summary>
            <div class="cg-faq-body">{esc(a)}</div>
          </details>"""
        for q, a in faqs)

    main = f"""      <div class="cg-about-page">
        <section class="cg-about-hero">
          <p class="cg-about-eyebrow">About Games</p>
          <h1 class="cg-about-title">Play first.<br>Sign up never.</h1>
          <p class="cg-about-lead">Games is a free browser arcade with
          {total:,} games you can start in a single click. No downloads, no
          installs, no accounts - just pick a title and play.</p>
          <div class="cg-about-cta">
            <a class="cg-btn cg-btn--lg" href="./">Browse all games</a>
            <a class="cg-btn cg-btn--lg" href="./?random=1">Surprise me</a>
          </div>
          <div class="cg-about-stats">
            <div class="cg-about-stat">
              <div class="cg-about-stat-num">{total:,}</div>
              <div class="cg-about-stat-label">games to play</div>
            </div>
            <div class="cg-about-stat">
              <div class="cg-about-stat-num">{len(cats)}</div>
              <div class="cg-about-stat-label">categories</div>
            </div>
            <div class="cg-about-stat">
              <div class="cg-about-stat-num">{sources}+</div>
              <div class="cg-about-stat-label">providers</div>
            </div>
            <div class="cg-about-stat">
              <div class="cg-about-stat-num">0</div>
              <div class="cg-about-stat-label">downloads needed</div>
            </div>
          </div>
        </section>

        <section class="cg-about-section">
          <h2 class="cg-about-h2">Find your next favourite</h2>
          <p class="cg-about-sub">From quick puzzle breaks to long multiplayer
          sessions, there is a corner of the catalogue for every mood.</p>
          <div class="cg-about-chips">
{cat_chips}
          </div>
        </section>

        <section class="cg-about-section">
          <h2 class="cg-about-h2">How it works</h2>
          <p class="cg-about-sub">Three steps, no friction.</p>
          <div class="cg-about-steps">
            <div class="cg-about-step">
              <div class="cg-about-step-num">1</div>
              <h3>Pick a game</h3>
              <p>Browse the rows, search by name or category, or hit Surprise me
              for a random pick.</p>
            </div>
            <div class="cg-about-step">
              <div class="cg-about-step-num">2</div>
              <h3>Play instantly</h3>
              <p>The game loads right in the page - nothing to download and
              nothing to set up.</p>
            </div>
            <div class="cg-about-step">
              <div class="cg-about-step-num">3</div>
              <h3>Keep the good ones</h3>
              <p>Heart a game to save it, and jump back in from Continue playing
              whenever you return.</p>
            </div>
          </div>
        </section>

        <section class="cg-about-section">
          <h2 class="cg-about-h2">Questions, answered</h2>
          <p class="cg-about-sub">The things people ask most.</p>
          <div class="cg-about-faq">
{faq_html}
          </div>
        </section>

        <section class="cg-about-band">
          <h2>Ready to play?</h2>
          <p>{total:,} games are waiting, and the first one is one click away.</p>
          <a class="cg-btn cg-btn--lg" href="./">Start playing</a>
        </section>
      </div>"""
    return page("About - Games",
                "About Games, a free browser games portal with thousands of "
                "instant-play titles.", main, "", "Home")


def main():
    games = load_games()

    # Build the catalogue bundle first so its content feeds the version token.
    data = json.dumps([{k: g[k] for k in ("slug", "title", "embed", "thumb",
                                          "categories", "rating", "source")} for g in games],
                      separators=(",", ":"))
    games_js = "window.CG_GAMES=" + data + ";\n"

    # The play page also needs the long-form fields (description, vote count,
    # keyword tags). Only ~half the catalogue has them, so they go in a separate
    # bundle that the play page alone loads - the home/catalogue pages stay on
    # the slim one.
    detail = [{"s": g["slug"], "v": g.get("votes"), "d": g.get("desc"),
               "t": g.get("tags")}
              for g in games
              if g.get("desc") or g.get("tags") or g.get("votes")]
    detail_js = ("window.CG_DETAIL={};" +
                 "(window.CG_DETAIL_ARR=" + json.dumps(detail, separators=(",", ":")) +
                 ").forEach(function(x){window.CG_DETAIL[x.s]=x;});\n")
    global VERSION
    VERSION = asset_version(games_js + detail_js)

    out = {
        "index.html": build_home(games),
        "play.html": build_play(games),
        "about.html": build_about(games),
    }
    # GitHub Pages serves 404.html for /<slug> game URLs; it is the same play
    # page, so the slug is read from the path and the game renders as usual.
    out["404.html"] = out["play.html"]
    for name, content in out.items():
        with open(os.path.join(ROOT, name), "w", encoding="utf-8") as f:
            f.write(content)
        print(f"wrote {name}  ({len(content)} bytes)")

    # The play page needs the catalogue client-side.
    with open(os.path.join(ROOT, "assets", "js", "cg-games.js"), "w",
              encoding="utf-8") as f:
        f.write(games_js)
    print(f"wrote assets/js/cg-games.js ({len(data)} bytes)  v={VERSION}")

    with open(os.path.join(ROOT, "assets", "js", "cg-detail.js"), "w",
              encoding="utf-8") as f:
        f.write(detail_js)
    print(f"wrote assets/js/cg-detail.js ({len(detail_js)} bytes)")


if __name__ == "__main__":
    main()
