#!/usr/bin/env python3
"""Generate the site's HTML pages from one shared shell.

index.html  catalogue: searchable, filterable grid of games
play.html   player: the game's own site in a full-width iframe

Both pages share the navbar/sidebar shell, so it lives here once. Edit this
script and re-run it rather than hand-editing the generated pages:

    python3 tools/build-home.py
"""
import datetime
import json
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA_FILE = os.path.join(ROOT, "data", "games.json")

# Bump alongside the ?v= on style.css / main.js so returning visitors (and
# Cloudflare, which caches assets for 4h) pick up changes.
VERSION = "11"

BUILD_STAMP = datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%d %H:%M:%SZ")

# The timestamp is here so you can view-source and tell whether the browser is
# showing a cached copy of an older deploy.
MARKER = (f"<!-- Generated by tools/build-home.py - edit that script, not this file. -->\n"
          f"<!-- build {BUILD_STAMP} -->")

BROWSE_LINKS = [
    ("Home", "/", "bi-house"),
    ("Top Games", "/?sort=rating", "bi-fire"),
    ("All Games", "/", "bi-grid"),
    ("Random", "/?random=1", "bi-shuffle"),
]


def head(title, description):
    return f"""  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{title}</title>
  <meta name="description" content="{description}">

  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css" rel="stylesheet">
  <link rel="icon" href="assets/img/favicon.png" type="image/png">
  <link href="assets/css/style.css?v={VERSION}" rel="stylesheet">"""


def navbar():
    # The brand doubles as the sidebar toggle: on <lg it opens the offcanvas,
    # from lg up it collapses the sidebar to an icon rail.
    return """  <!-- ================= Top navbar ================= -->
  <header class="rg-header sticky-top">
    <nav class="navbar navbar-expand-xl">
      <div class="container-fluid px-3 h-100">

        <button class="rg-icon-btn d-lg-none me-2" type="button"
                data-bs-toggle="offcanvas" data-bs-target="#sidebarLeft"
                aria-controls="sidebarLeft" aria-label="Open menu">
          <svg class="rg-svg"><use href="assets/svg/svg-map.svg#menu" xlink:href="assets/svg/svg-map.svg#menu"></use></svg>
        </button>

        <a class="navbar-brand rg-brand me-xl-3" href="/" id="rgSidebarToggle"
           role="button" aria-controls="sidebarLeft" aria-expanded="true"
           title="Hide or show the sidebar">
          <img src="assets/img/logo.png" width="58" height="28" alt="Games" class="rg-logo">
        </a>

        <div class="navbar-collapse d-none d-xl-flex" id="rgTopNav">
          <ul class="navbar-nav me-auto mb-2 mb-xl-0">
            <li class="nav-item"><a class="nav-link" href="/?sort=rating"><i class="bi bi-fire me-1"></i>Top Games</a></li>
            <li class="nav-item"><a class="nav-link" href="/"><i class="bi bi-grid me-1"></i>All Games</a></li>
            <li class="nav-item"><a class="nav-link" href="/?random=1"><i class="bi bi-shuffle me-1"></i>Random Game</a></li>
          </ul>

          <form class="rg-search my-2 my-xl-0 me-xl-3" role="search" onsubmit="return false;">
            <div class="input-group input-group-sm">
              <span class="input-group-text bg-transparent border-end-0">
                <svg class="rg-svg"><use href="assets/svg/svg-map.svg#search" xlink:href="assets/svg/svg-map.svg#search"></use></svg>
              </span>
              <input class="form-control border-start-0" type="search" placeholder="Search games" aria-label="Search games">
            </div>
          </form>

          <a class="rg-icon-btn my-2 my-xl-0" href="/about" aria-label="About">
            <i class="bi bi-info-circle"></i>
          </a>
        </div>
      </div>
    </nav>
  </header>"""


def sidebar(active_href):
    items = "\n".join(
        '          <li class="nav-item"><a class="nav-link{active}" href="{href}" title="{label}">'
        '<i class="bi {icon} rg-nav-icon"></i><span class="rg-nav-label">{label}</span></a></li>'.format(
            active=" active" if href == active_href and label == "Home" else "",
            href=href, icon=icon, label=label)
        for label, href, icon in BROWSE_LINKS
    )
    return f"""    <!-- ---------- Left sidebar (primary nav) ---------- -->
    <aside class="rg-sidebar rg-sidebar-start offcanvas-lg offcanvas-start" tabindex="-1"
           id="sidebarLeft" aria-label="Primary">
      <div class="offcanvas-header d-lg-none">
        <h2 class="offcanvas-title fs-6">Menu</h2>
        <button class="rg-icon-btn border-0" type="button" data-bs-dismiss="offcanvas" data-bs-target="#sidebarLeft" aria-label="Close">
          <svg class="rg-svg"><use href="assets/svg/svg-map.svg#close" xlink:href="assets/svg/svg-map.svg#close"></use></svg>
        </button>
      </div>

      <div class="rg-sidebar-title">Browse</div>
      <nav class="rg-nav">
        <ul class="nav flex-column">
{items}
        </ul>
      </nav>

      <div class="rg-sidebar-title rg-categories-title">Categories</div>
      <nav class="rg-nav rg-categories">
        <ul class="nav flex-column" id="rgCategories">
          <li class="nav-item"><span class="nav-link disabled">Loading…</span></li>
        </ul>
      </nav>
    </aside>"""


def page(title, description, body_main, scripts):
    return f"""<!doctype html>
<html lang="en" data-bs-theme="dark">
<head>
{MARKER}
{head(title, description)}
</head>
<body>

{navbar()}

  <!-- ================= Shell ================= -->
  <div class="rg-shell d-lg-flex" id="rgShell">

{sidebar('/')}

    <!-- ---------- Main content ---------- -->
{body_main}

  </div>

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
  <script src="assets/js/main.js?v={VERSION}"></script>
{scripts}
</body>
</html>
"""


def build_index(games):
    body = """    <main class="rg-main flex-grow-1">
      <h1 class="h4 mb-3" id="rgGridHeading">All games</h1>

      <div class="rg-grid" id="rgGrid">
        <p class="rg-empty">Loading games…</p>
      </div>
    </main>"""
    scripts = f'  <script src="assets/js/games.js?v={VERSION}"></script>'
    return page("Games", "Games - free unblocked browser games.", body, scripts)


def build_play():
    body = """    <main class="rg-main rg-main-play flex-grow-1">
      <div class="rg-stage">
        <div class="rg-player" id="rgPlayer">
          <div class="rg-player-note" id="rgPlayerNote">Loading game…</div>
        </div>

        <div class="rg-stage-bar">
          <h1 class="rg-stage-title" id="rgPlayTitle">Loading…</h1>
          <div class="rg-stage-actions" id="rgPlayActions">
            <a class="btn btn-sm btn-outline-secondary text-nowrap" href="/">
              <i class="bi bi-grid me-1"></i>All games
            </a>
          </div>
        </div>
      </div>

      <section class="rg-section">
        <h2 class="rg-section-title">Play next</h2>
        <div class="rg-grid rg-grid-wide" id="rgPlayNext">
          <p class="rg-empty">Loading…</p>
        </div>
      </section>
    </main>"""
    scripts = f'  <script src="assets/js/play.js?v={VERSION}"></script>'
    return page("Play · Games", "Play a free browser game on Games.", body, scripts)


def build_about():
    body = """    <main class="rg-main flex-grow-1">
      <div class="d-flex align-items-center justify-content-between mb-3">
        <h1 class="h4 mb-0">About</h1>
      </div>

      <div class="p-4 rounded-3 border" style="background-color: var(--rg-surface);">
        <h2 class="h5">About Games</h2>
        <p class="text-body-secondary">
          Games is a collection of free browser games you can play instantly - no downloads,
          no installs, no account. Pick a category from the sidebar, search for something
          specific, or hit Random Game for a surprise.
        </p>
        <p class="text-body-secondary mb-0">
          Games are provided by their own developers and run inside this page, so the only
          thing you need is a device and a bit of spare time.
        </p>
      </div>
    </main>"""
    return page("About · Games", "About Games - free unblocked browser games.", body, "")


def main():
    with open(DATA_FILE, encoding="utf-8") as fh:
        games = json.load(fh)

    for name, html in (("index.html", build_index(games)),
                       ("play.html", build_play()),
                       ("about.html", build_about())):
        with open(os.path.join(ROOT, name), "w", encoding="utf-8") as fh:
            fh.write(html)
        print(f"wrote {name}")

    print(f"{len(games)} games in catalogue")


if __name__ == "__main__":
    main()
