#!/usr/bin/env python3
"""Generate the site from the archived CrazyGames 2024 shell.

Rather than approximating the 2024 look, the pages here reuse the archived
markup and the archived stylesheet (assets/cg/archive.css, fetched by
tools/fetch-archive.py). Only two things differ from the archive:

  * branding  - our logo, our name, our favicon (no CrazyGames marks)
  * content   - our catalogue from data/games.json, and our own player

Everything else (header height, rail width, card geometry, type scale, the
player's main+sidebar split) is the archive's own CSS doing the work, so it
matches 1:1 instead of being eyeballed.

    python3 tools/fetch-archive.py     # once: pull css/fonts/bg/sprite
    python3 tools/build-archive.py     # then: emit the pages
"""
import datetime
import hashlib
import html
import json
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA_FILE = os.path.join(ROOT, "data", "games.json")
CG = "assets/cg"

# Cache-busting token for the local stylesheet/scripts. It is derived from the
# asset contents in main(), not hand-maintained: the old fixed "v=28" let a
# rebuilt cg.css sit behind a 4h max-age while the HTML (10min) updated, so
# returning visitors rendered the new markup with stale styles.
VERSION = "0"
BUILD_STAMP = datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%d %H:%M:%SZ")
MARKER = ("<!-- Generated by tools/build-archive.py - edit that script, not this file. -->\n"
          f"<!-- build {BUILD_STAMP} -->")


def asset_version(games_js):
    """sha1 of everything the pages link, so any change busts the cache."""
    h = hashlib.sha1()
    h.update(games_js.encode("utf-8"))
    for rel in ("assets/css/cg.css", "assets/js/cg-site.js", "assets/cg/archive.css"):
        try:
            with open(os.path.join(ROOT, rel), "rb") as fh:
                h.update(fh.read())
        except OSError:
            pass
    return h.hexdigest()[:10]

# --- rail (same entries and order as the archive, minus the account block) ----
RAIL = [
    ("Home", "./", "Home", True),
    ("Recently Played", "./?recent=1", "Recent", True),
    ("New", "./?sort=newest", "New", False),
    ("Trending", "./?sort=rating", "Trending", False),
    ("Favorites", "./favorites", "Favorites", True),
    ("__hr__",),
    ("2 Player", "./?category=Team", "2players", False),
    ("Action", "./?category=Action", "Action", False),
    ("Adventure", "./?category=Adventure", "Adventure", False),
    ("Casual", "./?category=Casual", "Casual", False),
    ("Puzzle", "./?category=Puzzle", "Puzzle", False),
    ("Shooting", "./?category=Shooter", "Shooting", False),
    ("Sports", "./?category=Sports", "Sports", False),
    ("Racing", "./?category=Racing", "Driving", False),
    ("Strategy", "./?category=Strategy", "TowerDefense", False),
    ("FPS", "./?category=FPS", "FPS", False),
    ("Horror", "./?category=Zombies", "Horror", False),
    (".io", "./?category=Agario%20Style", "io", False),
]

# --- our categories -> the archive's own category artwork ---------------------
CATEGORY_ICON = {
    "Action": "Action", "Adventure": "Adventure", "Arcade": "Flash",
    "Casual": "Casual", "Puzzle": "Puzzle", "Shooter": "Shooting",
    "2D Shooter": "Shooting", "FPS": "FPS", "Sports": "Sports",
    "Sport": "Sports", "Football": "Sports", "Soccer": "Soccer",
    "Baseball": "Sports", "Simulation": "Casual", "Sandbox": "Casual",
    "Emulator": "Controller", "Sci-Fi": "Space",
    "Basketball": "Basketball", "Racing": "Driving", "Car": "Car",
    "Bike": "Bike", "Tank": "Shooting", "Ships": "Pool",
    "Strategy": "TowerDefense", "Tower Defense": "TowerDefense",
    "Card": "Card", "Clicker": "Clicker", "Casual Games": "Casual",
    "Zombies": "Horror", "Horror": "Horror", "Space": "Action",
    "Survival": "Action", "RPG": "Adventure", "Fantasy": "Adventure",
    "Maze": "Escape", "Escape": "Escape", "Logic": "Puzzle",
    "Platform": "Stickman", "Running": "Stickman", "Retro": "Flash",
    "Classic": "Flash", "Mobile Games": "Controller",
    "Multiplayer": "Multiplayer", "Team": "Multiplayer",
    "Cooperative": "Multiplayer", "Battle Royale": "Shooting",
    "Fighting": "Action", "Agario Style": "io", "Moomoo.io Style": "io",
    "Splix Style": "io", "Diep Style": "io", "Crazy Games": "Originals",
    "Free For All": "Multiplayer", "Power-ups": "Action",
    "Upgrades": "Clicker", "Weird": "Flash", "Pixels": "Minecraft",
    "Minecraft": "Minecraft", "Chat": "Multiplayer", "Spectate": "Tags",
    "Simulation": "Controller", "Snake Games": "io", "3D": "Action",
    "Asteroids": "Flash", "Mahjong": "Mahjong", "Pool": "Pool",
    "Ocean": "Pool", "Beauty": "Beauty", "DressUp": "DressUp",
}
DEFAULT_ICON = "Tags"


def esc(s):
    return html.escape(str(s), quote=True)


def load_games():
    with open(DATA_FILE, encoding="utf-8") as f:
        games = json.load(f)
    for i, g in enumerate(games):
        g["_i"] = i
        g.setdefault("categories", [])
        g.setdefault("rating", None)
    return games


def play_url(g):
    return "./play?g=" + g["slug"]


def icon(name):
    return f"{CG}/icons/{CATEGORY_ICON.get(name, DEFAULT_ICON)}.svg"


# ---------------------------------------------------------------- page pieces --

def head(title, description, extra_css=""):
    return f"""  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{esc(title)}</title>
  <meta name="description" content="{esc(description)}">
  <meta name="theme-color" content="#0c0d14">
  <link rel="icon" href="assets/img/favicon.png" type="image/png">
  <link href="{CG}/archive.css?v={VERSION}" rel="stylesheet">
  <link href="assets/css/cg.css?v={VERSION}" rel="stylesheet">{extra_css}"""


def sprite():
    """Inline the archive's <symbol> defs so <use href="#id"> resolves.

    Our own heart symbol is appended so the favourite buttons on the cards can
    share one definition instead of repeating the path on every card.
    """
    path = os.path.join(ROOT, CG, "sprite.svg")
    try:
        with open(path, encoding="utf-8") as f:
            data = f.read()
    except OSError:
        data = '<svg xmlns="http://www.w3.org/2000/svg" style="display:none">'
    heart = ('<symbol id="cg-heart" viewBox="0 0 24 24">'
             '<path d="M12 21.35l-1.45-1.32C5.4 15.36 2 12.28 2 8.5 2 5.42 4.42 3 '
             '7.5 3c1.74 0 3.41.81 4.5 2.09C13.09 3.81 14.76 3 16.5 3 19.58 3 22 '
             '5.42 22 8.5c0 3.78-3.4 6.86-8.55 11.54L12 21.35z"></path></symbol>')
    return data.replace("</svg>", heart + "</svg>")


def header():
    """Archive header geometry: 60px tall, logo left, actions right."""
    return f"""  <header id="czyHeader" class="cg-header">
    <div class="cg-header-bar">
      <a class="cg-header-logo" href="./" aria-label="Games home">
        <img src="assets/img/logo.png" width="58" height="28" alt="Games">
      </a>
      <form class="cg-search" role="search" onsubmit="return false;">
        <input type="search" placeholder="Search games" aria-label="Search games"
               autocomplete="off" aria-controls="cgSearchResults">
        <div class="cg-search-results" id="cgSearchResults" role="listbox" hidden></div>
      </form>
      <div class="cg-header-actions">
        <a class="cg-iconbtn cg-admin-link" href="./admin" aria-label="Admin panel" title="Admin panel">
          <svg viewBox="0 0 24 24" width="22" height="22" fill="currentColor" aria-hidden="true"><path d="M19.14 12.94a7.5 7.5 0 0 0 .06-.94 7.5 7.5 0 0 0-.06-.94l2.03-1.58a.5.5 0 0 0 .12-.64l-1.92-3.32a.5.5 0 0 0-.6-.22l-2.39.96a7 7 0 0 0-1.62-.94l-.36-2.54a.5.5 0 0 0-.5-.42h-3.84a.5.5 0 0 0-.5.42l-.36 2.54c-.58.24-1.12.55-1.62.94l-2.39-.96a.5.5 0 0 0-.6.22L2.74 8.84a.5.5 0 0 0 .12.64l2.03 1.58a7.5 7.5 0 0 0 0 1.88l-2.03 1.58a.5.5 0 0 0-.12.64l1.92 3.32c.13.22.39.3.6.22l2.39-.96c.5.39 1.04.7 1.62.94l.36 2.54c.04.24.25.42.5.42h3.84c.25 0 .46-.18.5-.42l.36-2.54c.58-.24 1.12-.55 1.62-.94l2.39.96c.22.08.48 0 .6-.22l1.92-3.32a.5.5 0 0 0-.12-.64l-2.03-1.58zM12 15.5A3.5 3.5 0 1 1 12 8.5a3.5 3.5 0 0 1 0 7z"/></svg>
        </a>
        <a class="cg-iconbtn" href="./?random=1" aria-label="Random game" title="Random game">
          <svg viewBox="0 0 24 24" width="22" height="22" fill="currentColor" aria-hidden="true"><path d="M17 3h4v4h-2V6.4l-3.3 3.3-1.4-1.4L17.6 5H17zM3 5h4.2l3.3 3.3-1.4 1.4L6.4 7H3zm14 10.6 1.4-1.4 1.6 1.6V14h2v4h-4v-2h.6zM3 19h3.4l4.1-4.1 1.4 1.4L7.2 21H3z"/></svg>
        </a>
        <a class="cg-iconbtn" href="./about" aria-label="About" title="About">
          <svg viewBox="0 0 24 24" width="22" height="22" fill="currentColor" aria-hidden="true"><path d="M12 2a10 10 0 1 0 0 20 10 10 0 0 0 0-20zm1 15h-2v-6h2zm0-8h-2V7h2z"/></svg>
        </a>
      </div>
    </div>
  </header>"""


def rail(active=""):
    rows = []
    for item in RAIL:
        if item[0] == "__hr__":
            rows.append('      <hr class="cg-rail-hr">')
            continue
        label, href, icon_name, _ = item
        on = " cg-active" if label.lower() == active.lower() else ""
        rows.append(
            f'      <a class="cg-rail-item{on}" href="{href}" aria-label="{esc(label)}">'
            f'<img src="{CG}/icons/{icon_name}.svg" loading="lazy" alt="" width="28" height="28">'
            f'<div class="cg-rail-label">{esc(label)}</div></a>')
    return f"""  <nav id="mainNav" class="cg-rail" aria-label="Main">
    <div class="cg-rail-inner">
{chr(10).join(rows)}
    </div>
  </nav>"""


def card(g):
    cats = "|".join(g["categories"])
    return (f'<a class="cg-card" href="{play_url(g)}" '
            f'data-title="{esc(g["title"].lower())}" data-cats="{esc(cats)}" '
            f'data-rating="{g["rating"] or 0}" data-i="{g["_i"]}">'
            f'<div class="cg-card-title">{esc(g["title"])}</div>'
            f'<img class="cg-card-img" loading="lazy" src="{esc(g["thumb"])}" '
            f'alt="{esc(g["title"])}">'
            f'<button class="cg-fav" type="button" data-fav="{esc(g["slug"])}" '
            f'aria-label="Add {esc(g["title"])} to favourites" aria-pressed="false">'
            f'<svg viewBox="0 0 24 24" aria-hidden="true">'
            f'<use href="#cg-heart"></use></svg></button></a>')


def carousel(title, games, more_href=""):
    more = (f'<a class="cg-more" href="{more_href}">View more</a>'
            if more_href else "")
    items = "\n".join(f"          <li>{card(g)}</li>" for g in games)
    return f"""      <section class="cg-section">
        <div class="cg-section-head">
          <h2 class="cg-section-title">{esc(title)}</h2>{more}
        </div>
        <div class="cg-carousel">
          <ul class="cg-carousel-track">
{items}
          </ul>
        </div>
      </section>"""


def grid_section(title, games, more_href=""):
    more = (f'<a class="cg-more" href="{more_href}">View more</a>'
            if more_href else "")
    items = "\n".join(f"          <li>{card(g)}</li>" for g in games)
    return f"""      <section class="cg-section">
        <div class="cg-section-head">
          <h2 class="cg-section-title">{esc(title)}</h2>{more}
        </div>
        <ul class="cg-grid">
{items}
        </ul>
      </section>"""


def footer():
    return """  <footer class="cg-footer">
    <div class="cg-footer-inner">
      <p class="cg-footer-name">Games</p>
      <p class="cg-footer-note">A free browser games portal.</p>
    </div>
  </footer>"""


def admin_dialog(with_close=True):
    """Admin search/rate dialog, shared by the modal and the standalone page."""
    close = """        <button class="cg-admin-close" type="button" aria-label="Close admin panel">
          <svg viewBox="0 0 24 24" width="20" height="20" fill="currentColor" aria-hidden="true"><path d="M19 6.41 17.59 5 12 10.59 6.41 5 5 6.41 10.59 12 5 17.59 6.41 19 12 13.41 17.59 19 19 17.59 13.41 12z"/></svg>
        </button>""" if with_close else ""
    return f"""      <div class="cg-admin-head">
        <h2 class="cg-admin-title">Admin panel</h2>
{close}
      </div>
      <p class="cg-admin-note">Search the catalogue and click a star to set a game's
        rating. Ratings are saved in this browser and shown on the play page.</p>
      <input class="cg-admin-search" type="search" placeholder="Search games to rate"
             aria-label="Search games to rate" autocomplete="off">
      <ul class="cg-admin-results"></ul>"""


def admin_modal():
    """Overlay version, present on every page and opened with Ctrl+Alt+A."""
    return f"""  <div class="cg-admin" id="cgAdmin" role="dialog" aria-modal="true"
       aria-label="Admin panel" hidden>
    <div class="cg-admin-dialog">
{admin_dialog()}
    </div>
  </div>"""


def page(title, description, main, scripts, rail_active="Home", main_class="",
         admin_overlay=True):
    cls = ("cg-main " + main_class).strip()
    modal = admin_modal() if admin_overlay else ""
    return f"""<!doctype html>
<html lang="en">
<head>
{MARKER}
{head(title, description)}
</head>
<body>
{sprite()}
{header()}

  <div class="cg-shell">
{rail(rail_active)}

    <main class="{cls}">
{main}
    </main>
  </div>

{footer()}
{modal}

  <script src="assets/js/cg-games.js?v={VERSION}"></script>
  <script src="assets/js/cg-site.js?v={VERSION}"></script>
  <script src="assets/js/cg-admin.js?v={VERSION}"></script>{scripts}
</body>
</html>
"""


# ------------------------------------------------------------------- builders --

def build_home(games):
    # The catalogue is ~12k games, so the page ships the data (cg-games.js) and
    # lets cg-site.js render the cards. Server-rendering every card would make
    # index.html megabytes of markup for a grid the client filters anyway; the
    # carousels below are filled from the same bundle on load.
    parts = []
    parts.append("""      <section class="cg-section" data-row="new">
        <div class="cg-section-head">
          <h2 class="cg-section-title">New games</h2>
          <a class="cg-more" href="./?sort=newest">View more</a>
        </div>
        <div class="cg-carousel"><ul class="cg-carousel-track" id="cgNewTrack"></ul></div>
      </section>""")

    parts.append("""      <section class="cg-section" data-row="top">
        <div class="cg-section-head">
          <h2 class="cg-section-title">Top games</h2>
          <a class="cg-more" href="./?sort=rating">View more</a>
        </div>
        <div class="cg-carousel"><ul class="cg-carousel-track" id="cgTopTrack"></ul></div>
      </section>""")

    rows = [
        (".io Games", "Agario Style"),
        ("Action Games", "Action"),
        ("Puzzle Games", "Puzzle"),
        ("Shooting Games", "Shooter"),
        ("Sports Games", "Sports"),
        ("Racing Games", "Racing"),
        ("Casual Games", "Casual"),
    ]
    for label, cat in rows:
        parts.append(f"""      <section class="cg-section" data-row="cat">
        <div class="cg-section-head">
          <h2 class="cg-section-title">{esc(label)}</h2>
          <a class="cg-more" href="./?category={cat.replace(' ', '%20')}">View more</a>
        </div>
        <div class="cg-carousel"><ul class="cg-carousel-track"
          data-cat="{esc(cat)}"></ul></div>
      </section>""")

    parts.append("""      <section class="cg-section" data-row="best">
        <div class="cg-section-head">
          <h2 class="cg-section-title">Play our best games</h2>
        </div>
        <ul class="cg-grid" id="cgBestGrid"></ul>
      </section>""")

    # Every game, rendered in pages by the client so the DOM stays small. A big
    # category (Casual ~25k) would otherwise build every card and image at once.
    parts.append("""      <section class="cg-section" id="cgAllGames" hidden>
        <div class="cg-section-head">
          <h2 class="cg-section-title" id="cgAllTitle">All games</h2>
          <span class="cg-more" id="cgAllCount"></span>
        </div>
        <ul class="cg-grid" id="cgAllGrid"></ul>
        <p class="cg-loadmore-wrap">
          <button class="cg-btn" type="button" id="cgAllMore" hidden>Load more</button>
        </p>
      </section>""")

    return page("Games - Free Online Games",
                "Play free browser games: action, puzzle, shooting, sports and more.",
                "\n".join(parts), "", "Home")


def build_play(games):
    params_js = """
  <script>
  (function () {
    var p = new URLSearchParams(location.search).get('g');
    var games = window.CG_GAMES || [];
    var g = games.filter(function (x) { return x.slug === p; })[0] || games[0];
    if (!g) return;
    document.title = g.title + ' - Games';
    document.getElementById('cgStageTitle').textContent = g.title;

    // Rating row and category breadcrumb values. An admin rating (1-5, set via
    // Ctrl+Alt+A) overrides the catalogue's own 0-10 value.
    var mine = window.CGAdmin ? window.CGAdmin.ratingFor(g.slug) : 0;
    document.getElementById('cgMetaRating').innerHTML = mine
      ? '<b>' + mine.toFixed(1) + '</b><span class="cg-votes">(out of 5)</span>'
      : g.rating
        ? '<b>' + g.rating.toFixed(1) + '</b><span class="cg-votes">(out of 10)</span>'
        : 'Not rated yet';
    document.getElementById('cgMetaSource').textContent = g.source || 'Unknown';
    document.getElementById('cgMetaCats').innerHTML =
      (g.categories || []).map(function (c) {
        return '<a class="cg-chip" href="./?category=' + encodeURIComponent(c) + '">' + c + '</a>';
      }).join('') || '<span>Casual</span>';
    document.getElementById('cgMetaDesc').textContent =
      'Play ' + g.title + ' for free in your browser. No download, no install.';

    document.getElementById('cgFrame').src = g.embed;

    // Related first (shared category), then the rest, so the section shows
    // genre-mates instead of the catalogue's first alphabetical entries.
    var cats = g.categories || [];
    var others = games.filter(function (x) { return x.slug !== g.slug; });
    var sameCat = others.filter(function (x) {
      return (x.categories || []).some(function (c) { return cats.indexOf(c) >= 0; });
    });
    var related = sameCat.concat(others.filter(function (x) {
      return sameCat.indexOf(x) < 0;
    }));

    function cards(list) {
      return list.map(function (x) {
        return '<li><a class="cg-card" href="./play?g=' + x.slug + '">' +
          '<div class="cg-card-title">' + x.title + '</div>' +
          '<img class="cg-card-img" loading="lazy" src="' + x.thumb + '" alt="">' +
          '<button class="cg-fav" type="button" data-fav="' + x.slug +
          '" aria-label="Add to favourites" aria-pressed="false">' +
          '<svg viewBox="0 0 24 24" aria-hidden="true">' +
          '<use href="#cg-heart"></use></svg></button></a></li>';
      }).join('');
    }

    document.getElementById('cgSideList').innerHTML = cards(related.slice(0, 20));
    document.getElementById('cgMoreGrid').innerHTML = cards(related.slice(0, 24));
  })();
  </script>"""

    main = """      <div class="cg-play">
        <div class="cg-play-main">
          <div class="cg-player">
            <div class="cg-loader" id="cgLoader" role="progressbar" aria-label="Loading game">
              <span class="cg-spinner">
                <svg viewBox="22 22 44 44"><circle cx="44" cy="44" r="20.2"
                  fill="none" stroke-width="3.6"></circle></svg>
              </span>
            </div>
            <iframe id="cgFrame" class="cg-frame" title="Game" allowfullscreen
                    allow="autoplay; fullscreen; gamepad; clipboard-write"></iframe>
          </div>
          <div class="cg-info" id="gameInfoContainer">
            <div class="cg-info-head">
              <h1 class="cg-info-title" id="cgStageTitle">Loading...</h1>
              <div class="cg-info-actions">
                <button class="cg-pill cg-pill-fav" type="button" id="cgFavToggle" hidden
                        aria-pressed="false">
                  <svg viewBox="0 0 24 24" aria-hidden="true"><use href="#cg-heart"></use></svg><span>Favorite</span>
                </button>
                <button class="cg-pill" type="button" id="cgFullscreen">
                  <svg viewBox="0 0 24 24" aria-hidden="true"><path d="M7 14H5v5h5v-2H7v-3zm-2-4h2V7h3V5H5v5zm12 7h-3v2h5v-5h-2v3zM14 5v2h3v3h2V5h-5z"/></svg><span>Fullscreen</span>
                </button>
                <a class="cg-pill" href="./?random=1">
                  <svg viewBox="0 0 24 24" aria-hidden="true"><path d="M17 3H5a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2V8l-5-5zm-3 15a3 3 0 1 1 0-6 3 3 0 0 1 0 6zm2-9H5V5h9l2 2v2z"/></svg><span>Random game</span>
                </a>
              </div>
            </div>
            <div class="cg-info-rows">
              <div class="cg-info-row"><div class="cg-info-label">Rating:</div><div class="cg-info-value" id="cgMetaRating"></div></div>
              <div class="cg-info-row"><div class="cg-info-label">Released:</div><div class="cg-info-value">Free to play</div></div>
              <div class="cg-info-row"><div class="cg-info-label">Technology:</div><div class="cg-info-value">HTML5</div></div>
              <div class="cg-info-row"><div class="cg-info-label">Source:</div><div class="cg-info-value" id="cgMetaSource"></div></div>
              <div class="cg-info-row"><div class="cg-info-label">Categories:</div><div class="cg-info-value" id="cgMetaCats"></div></div>
            </div>
            <hr class="cg-info-divider">
            <div class="cg-info-desc"><p id="cgMetaDesc"></p></div>
            <hr class="cg-info-divider">
            <div class="cg-info-more">
              <h2 class="cg-info-more-title">More games</h2>
              <ul class="cg-grid cg-info-grid" id="cgMoreGrid"></ul>
            </div>
          </div>
        </div>
        <aside class="cg-play-side">
          <h2 class="cg-side-title">More games</h2>
          <ul class="cg-side-list" id="cgSideList"></ul>
        </aside>
      </div>"""
    return page("Play - Games", "Play a free browser game.",
                main, params_js, "Home", "cg-main-play")


def build_about(games):
    main = f"""      <div class="cg-about">
        <h1>About</h1>
        <p>Games is a free browser games portal with {len(games)} games you can
        play instantly, no download required.</p>
        <p><a class="cg-btn" href="./">Browse all games</a></p>
      </div>"""
    return page("About - Games", "About Games.", main, "", "Home")


def build_favorites(games):
    main = """      <div class="cg-fav-page">
        <div class="cg-section-head">
          <h2 class="cg-section-title">Favorites</h2>
          <span class="cg-more" id="cgFavCount"></span>
        </div>
        <p class="cg-fav-empty" id="cgFavEmpty" hidden>
          You haven't saved any games yet. Tap the heart on a game card to keep
          it here.
        </p>
        <ul class="cg-grid" id="cgFavGrid"></ul>
        <p class="cg-fav-clear-wrap">
          <button class="cg-btn" type="button" id="cgFavClear" hidden>Clear all</button>
        </p>
      </div>"""
    return page("Favorites - Games", "Your saved games.", main, "", "Favorites",
                "cg-main-fav")


def build_admin(games):
    """Standalone admin page: the same dialog, without the overlay."""
    main = f"""      <div class="cg-admin-page">
        <div class="cg-admin-dialog" id="cgAdmin">
{admin_dialog(with_close=False)}
        </div>
      </div>"""
    return page("Admin - Games", "Admin panel.", main, "", "Home", "cg-main-admin",
                admin_overlay=False)


def main():
    games = load_games()

    # Build the catalogue bundle first so its content feeds the version token.
    data = json.dumps([{k: g[k] for k in ("slug", "title", "embed", "thumb",
                                          "categories", "rating", "source")} for g in games],
                      separators=(",", ":"))
    games_js = "window.CG_GAMES=" + data + ";\n"
    global VERSION
    VERSION = asset_version(games_js)

    out = {
        "index.html": build_home(games),
        "play.html": build_play(games),
        "about.html": build_about(games),
        "favorites.html": build_favorites(games),
        "admin.html": build_admin(games),
    }
    for name, content in out.items():
        with open(os.path.join(ROOT, name), "w", encoding="utf-8") as f:
            f.write(content)
        print(f"wrote {name}  ({len(content)} bytes)")

    # The play page needs the catalogue client-side.
    with open(os.path.join(ROOT, "assets", "js", "cg-games.js"), "w",
              encoding="utf-8") as f:
        f.write(games_js)
    print(f"wrote assets/js/cg-games.js ({len(data)} bytes)  v={VERSION}")


if __name__ == "__main__":
    main()
